# Setup
name: 麦索的麦田
ocale: "en"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-toc
  - jekyll-archives

#Others
markdown: kramdown

jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - cotegory
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'
